//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickLook.Plugin.JupyterNotebookViewer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickLook.Plugin.JupyterNotebookViewer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&apos;utf-8&apos; /&gt;
        ///    &lt;title&gt;nbviewer.js&lt;/title&gt;
        ///    &lt;style type=&apos;text/css&apos;&gt;{{prism_min_css}}&lt;/style&gt;
        ///    &lt;script &gt;{{marked_min_js}}&lt;/script&gt;
        ///    &lt;script data-manual&gt;{{prism_min_js}}&lt;/script&gt;
        ///    &lt;script data-manual&gt;{{prism_python_min_js}}&lt;/script&gt;
        ///    &lt;style type=&apos;text/css&apos;&gt;{{katex_min_css}}&lt;/style&gt;
        ///    &lt;script data-manual&gt;{{katex_min_js}}&lt;/script&gt;
        ///    &lt;script type=&apos;text/javascript&apos;&gt;{{nbv_js}}&lt;/script&gt;
        ///    &lt;style type=&apos;text/css&apos;&gt;
        ///        body {
        ///      [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string json2html {
            get {
                return ResourceManager.GetString("json2html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @font-face{font-family:KaTeX_AMS;src:url(fonts/KaTeX_AMS-Regular.woff2) format(&quot;woff2&quot;),url(fonts/KaTeX_AMS-Regular.woff) format(&quot;woff&quot;),url(fonts/KaTeX_AMS-Regular.ttf) format(&quot;truetype&quot;);font-weight:400;font-style:normal}@font-face{font-family:KaTeX_Caligraphic;src:url(fonts/KaTeX_Caligraphic-Bold.woff2) format(&quot;woff2&quot;),url(fonts/KaTeX_Caligraphic-Bold.woff) format(&quot;woff&quot;),url(fonts/KaTeX_Caligraphic-Bold.ttf) format(&quot;truetype&quot;);font-weight:700;font-style:normal}@font-face{font-family:KaTeX_Caligraphic;sr [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string katex_min_css {
            get {
                return ResourceManager.GetString("katex_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 !function(t,e){&quot;object&quot;==typeof exports&amp;&amp;&quot;object&quot;==typeof module?module.exports=e():&quot;function&quot;==typeof define&amp;&amp;define.amd?define([],e):&quot;object&quot;==typeof exports?exports.katex=e():t.katex=e()}(&quot;undefined&quot;!=typeof self?self:this,function(){return function(t){var e={};function r(a){if(e[a])return e[a].exports;var n=e[a]={i:a,l:!1,exports:{}};return t[a].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.m=t,r.c=e,r.d=function(t,e,a){r.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:a})},r.r=function(t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string katex_min_js {
            get {
                return ResourceManager.GetString("katex_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function(){function e(e){this.tokens=[],this.tokens.links={},this.options=e||a.defaults,this.rules=p.normal,this.options.gfm&amp;&amp;(this.options.tables?this.rules=p.tables:this.rules=p.gfm)}function t(e,t){if(this.options=t||a.defaults,this.links=e,this.rules=u.normal,this.renderer=this.options.renderer||new n,this.renderer.options=this.options,!this.links)throw new Error(&quot;Tokens array requires a `links` property.&quot;);this.options.gfm?this.options.breaks?this.rules=u.breaks:this.rules=u.gfm:this.options.pedantic&amp; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string marked_min_js {
            get {
                return ResourceManager.GetString("marked_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 const nbv_constructor = (function(document, deps) {
        ///    &quot;use strict&quot;;
        ///
        ///    var d = document;
        ///    var st = {}; // settings
        ///
        ///    function render_ipynb(obj, target, settings) {
        ///        st = settings || {};
        ///
        ///        st.nbformat = obj.nbformat;
        ///        if (st.nbformat &lt; 3) {
        ///            throw new Error(&apos;Format of the notebook too old&apos;);
        ///        }
        ///
        ///        if (st.nbformat &gt; 3) {
        ///            st.lang = (obj.metadata.kernelspec || {&apos;language&apos;: null}).language;
        ///        }
        ///
        ///        // wipe all inner elements of our tar [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string nbv_js {
            get {
                return ResourceManager.GetString("nbv_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code[class*=language-],pre[class*=language-]{color:#000;background:0 0;text-shadow:0 1px #fff;font-family:Consolas,Monaco,&apos;Andale Mono&apos;,&apos;Ubuntu Mono&apos;,monospace;text-align:left;white-space:pre;word-spacing:normal;word-break:normal;word-wrap:normal;line-height:1.5;-moz-tab-size:4;-o-tab-size:4;tab-size:4;-webkit-hyphens:none;-moz-hyphens:none;-ms-hyphens:none;hyphens:none}code[class*=language-] ::-moz-selection,code[class*=language-]::-moz-selection,pre[class*=language-] ::-moz-selection,pre[class*=language-] [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string prism_min_css {
            get {
                return ResourceManager.GetString("prism_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 var _self=&quot;undefined&quot;!=typeof window?window:&quot;undefined&quot;!=typeof WorkerGlobalScope&amp;&amp;self instanceof WorkerGlobalScope?self:{},Prism=function(){var e=/\blang(?:uage)?-(\w+)\b/i,t=0,a=_self.Prism={util:{encode:function(e){return e instanceof n?new n(e.type,a.util.encode(e.content),e.alias):&quot;Array&quot;===a.util.type(e)?e.map(a.util.encode):e.replace(/&amp;/g,&quot;&amp;amp;&quot;).replace(/&lt;/g,&quot;&amp;lt;&quot;).replace(/\u00a0/g,&quot; &quot;)},type:function(e){return Object.prototype.toString.call(e).match(/\[object (\w+)\]/)[1]},objId:function(e){ret [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string prism_min_js {
            get {
                return ResourceManager.GetString("prism_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prism.languages.python={&quot;triple-quoted-string&quot;:{pattern:/&quot;&quot;&quot;[\s\S]+?&quot;&quot;&quot;|&apos;&apos;&apos;[\s\S]+?&apos;&apos;&apos;/,alias:&quot;string&quot;},comment:{pattern:/(^|[^\\])#.*/,lookbehind:!0},string:{pattern:/(&quot;|&apos;)(?:\\\\|\\?[^\\\r\n])*?\1/,greedy:!0},&quot;function&quot;:{pattern:/((?:^|\s)def[ \t]+)[a-zA-Z_][a-zA-Z0-9_]*(?=\()/g,lookbehind:!0},&quot;class-name&quot;:{pattern:/(\bclass\s+)[a-z0-9_]+/i,lookbehind:!0},keyword:/\b(?:as|assert|async|await|break|class|continue|def|del|elif|else|except|exec|finally|for|from|global|if|import|in|is|lambda|pass|print|raise|r [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string prism_python_min_js {
            get {
                return ResourceManager.GetString("prism_python_min_js", resourceCulture);
            }
        }
    }
}
